peers:
  - http://localhost:8001
  - http://localhost:8002
  - http://localhost:8003
front-server:
  http://localhost:9999

http:
  defaultReplicas : 50
  defaultBasePath : "/cache/"

api: "cache"

online-servers:
  - port: 8001
    ip: localhost
    api: false

  - port: 8002
    ip: localhost
    api: false

  - port: 8003
    ip: localhost
    api: true

redis:
  addr:
  port:
  user:
  pwd:


mysql:
  password: 123456
  user: root
  database: CacheDB