#与用户交互
front-server:
  http://localhost:9969

http:
  defaultReplicas : 50
  defaultBasePath : "/cache/"

api: "cache"
# 缓存服务器
online-servers:
  - port: 8001
    ip: localhost
    api: false

  - port: 8002
    ip: localhost
    api: false

  - port: 8004
    ip: localhost
    api: false

  - port: 8003
    ip: localhost
    api: true

redis:
  addr:
  port:
  user:
  pwd:


mysql:
  password: 123456
  user: root
  database: CacheDB